---
title: "pdxBlacklist"
author: "Max Salm"
date: '`r paste("Version 1.0:", format(Sys.time(), "%d %B, %Y"))`'
output:
  word_document:
    toc: yes
    toc_depth: '2'
  pdf_document:
    toc: yes
  html_document:
    number_sections: yes
    theme: spacelab
    toc: yes
    toc_depth: 2
    toc_float: yes
csl: nature.csl
bibliography: pdxBlacklist.bib
---


pdxBlacklist
========

Patient-derived xenograft models are extremely valuable to immunology and oncology [@Townsend2016]. However, cross-contamination between host and graft tissue is inevitable [@Conway2012]. Accordingly, sequencing data generated from these samples likely represent a mixture of mouse and human sequences.

*pdxBlacklist* catalogues genomic variation artefacts that arise by aligning mouse-derived short-read sequencing data to the human genome. To achieve this, mouse strain-specific short-reads generated by the [Mouse Genome Project](http://www.sanger.ac.uk/science/data/mouse-genomes-project) [@Keane2011] are aligned to the human genome, before identifying likely artefacts (e.g. SNVs and indels). The resulting variation catalogue enables annotation of existing variation datasets using tools such as *Vcfanno* [@Pedersen2016]. 

The *pdxBlacklist* pipeline is based on the bcbio-nextgen [pipeline](http://bcbio-nextgen.readthedocs.io/en/latest/), which affords great analytical flexibility in the choice of genome builds, aligners and variant callers. Currently, the defaults are set to:

* Genome: `hg19`
* Aligner: `BWA`
* Caller: `VarDict` [@Lai2016]

To run the *pdxBlacklist* pipeline, exectute the following:

    python pdxBlacklist.py --strain NOD_ShiLtJ

where `--strain` specifies the mouse strain of interest.

Features
--------

- A choice of mouse strains (currently 40)
- Diverse variant analysis pipelines

Installation
------------
The scripts in this project have been developed and tested on an 8-core server with 30GB RAM running Ubuntu 14.04.5 LTS (GNU/Linux 3.19.0-74-generic x86_64).

To install the *pdxBlacklist* pipeline, please run the following:

    scripts/0_setup_bcbio.sh


Contribute
----------

- Issue Tracker: https://github.com/MaxSalm/pdxBlacklist/issues
- Source Code: https://github.com/MaxSalm/pdxBlacklist

Support
-------

If you are having issues, please let us know.

License
-------

The project is licensed under the GPL license.

Citation
-------

Paper in press

References
-------




